name: Build and Publish Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine next version
        id: version
        uses: einaregilsson/next-version@v1
        with:
          tag_prefix: "v"
          default_bump: "patch"

      - name: Build Docker image
        run: |
          docker build -t client-onboarding-tool:${{ steps.version.outputs.next_version }} .
          docker tag client-onboarding-tool:${{ steps.version.outputs.next_version }} ${{ secrets.DOCKERHUB_USERNAME }}/client-onboarding-tool:${{ steps.version.outputs.next_version }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/client-onboarding-tool:${{ steps.version.outputs.next_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/client-onboarding-tool:latest
