name: Build and Publish Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t client-onboarding-tool:latest .
          docker tag client-onboarding-tool:latest ${{ secrets.DOCKERHUB_USERNAME }}/client-onboarding-tool:latest

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/client-onboarding-tool:latest
