name: Build and Publish Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest tag
        id: get-latest-tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Determine next version
        id: determine-next-version
        uses: JasonEtco/create-or-update-version@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.get-latest-tag.outputs.tag }}

      - name: Build Docker image
        run: |
          docker build -t client-onboarding-tool:${{ steps.determine-next-version.outputs.version }} .
          docker tag client-onboarding-tool:${{ steps.determine-next-version.outputs.version }} ${{ secrets.DOCKERHUB_USERNAME }}/client-onboarding-tool:${{ steps.determine-next-version.outputs.version }}
        
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/client-onboarding-tool:${{ steps.determine-next-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/client-onboarding-tool:latest
